#pragma once
#include "wsa_env.h"
#include <iostream>



struct ACEitem
{
	ACCESS_ALLOWED_ACE pAce;
	SID_NAME_USE SidType;
	CHAR Name[64];
};

static LPCSTR use_name_labels[] = {
	"SidTypeUser",
	"SidTypeGroup",
	"SidTypeDomain",
	"SidTypeAlias",
	"SidTypeWellKnownGroup",
	"SidTypeDeletedAccount",
	"SidTypeInvalid",
	"SidTypeUnknown",
	"SidTypeComputer",
	"SidTypeLabel"
};

static LPCSTR ace_type_labels[] = {
	"ACCESS_ALLOWED_ACE_TYPE",
	"ACCESS_ALLOWED_ACE_TYPE",
	"ACCESS_DENIED_ACE_TYPE",
	"SYSTEM_AUDIT_ACE_TYPE",
	"SYSTEM_ALARM_ACE_TYPE",
	"ACCESS_MAX_MS_V2_ACE_TYPE",
	"ACCESS_ALLOWED_COMPOUND_ACE_TYPE",
	"ACCESS_MAX_MS_V3_ACE_TYPE",
	"ACCESS_MIN_MS_OBJECT_ACE_TYPE",
	"ACCESS_ALLOWED_OBJECT_ACE_TYPE",
	"ACCESS_DENIED_OBJECT_ACE_TYPE",
	"SYSTEM_AUDIT_OBJECT_ACE_TYPE",
	"SYSTEM_ALARM_OBJECT_ACE_TYPE",
	"ACCESS_MAX_MS_OBJECT_ACE_TYPE",
	"ACCESS_MAX_MS_V4_ACE_TYPE",
	"ACCESS_MAX_MS_ACE_TYPE",
	"ACCESS_ALLOWED_CALLBACK_ACE_TYPE",
	"ACCESS_DENIED_CALLBACK_ACE_TYPE",
	"ACCESS_ALLOWED_CALLBACK_OBJECT_ACE_TYPE",
	"ACCESS_DENIED_CALLBACK_OBJECT_ACE_TYPE",
	"SYSTEM_AUDIT_CALLBACK_ACE_TYPE",
	"SYSTEM_ALARM_CALLBACK_ACE_TYPE",
	"SYSTEM_AUDIT_CALLBACK_OBJECT_ACE_TYPE",
	"SYSTEM_ALARM_CALLBACK_OBJECT_ACE_TYPE",
	"SYSTEM_MANDATORY_LABEL_ACE_TYPE",
	"ACCESS_MAX_MS_V5_ACE_TYPE"
};

const char *access_right(DWORD Mask);

DWORD AccessRightArray[];

void view_accrights(DWORD Mask);